version: '3'
services:
  cli-to-rest:
    build: ./app
    container_name: cli-to-rest
    environment:
      FLASK_DEBUG: True
      PYTHONUNBUFFERED: True
    restart: on-failure
    image: kubikrubikvkube/cli-to-rest:v0.1

    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: python main_controller.py